### PR TITLE
Null Safety

### PR DESCRIPTION
**Pull request by nizwar**
Support for null safety

### CODE REVIEW

**Comment by combi-35** [comment]
@chinloyal any chance we can move on with this?
Would be very thankful!

**Comment by lpickford-pixelbeard** [comment]
subscribing to this thread for updates

**Comment by JEuler** [comment]
Any news on merging it? Or any additional work that should be done?

**Comment by miquelbeltran** [comment]
I ended up forking nizwar:master and referencing my fork directly.

It is a pitty Pusher is not investing in an official Flutter plugin, being a paid service! Competitors like getstream.io have officially supported plugins.

**Review by micodev — APPROVED** [review]

**Comment by craines** [comment]
@chinloyal How do I download the updated version?

**Comment by pishguy** [comment]
@craines 

```dart
  pusher_client:
    git:
      url: https://github.com/nizwar/pusher_client.git

```

**Pull request merged**
